### PR TITLE
ADD volume backup commands parser

### PR DESCRIPTION
**Pull request by sp6370**
This pull request's migrates the python cli tool used for creating Anubis playground IDE's volume backups.  

Ref. https://github.com/AnubisLMS/VolumeBackup

### CODE REVIEW

**Comment by wabscale** [comment]
This is a good start. I'm going to adjust things a bit so that it is using the built in flask templates thing, instead of us doing our own thing with jinja.

**Comment by sp6370** [comment]
> This is a good start. I'm going to adjust things a bit so that it is using the built in flask templates thing, instead of us doing our own thing with jinja.

I would love to jump in if you don't mind pointing the direction. I have worked with flask before and I would be able to pick it up.

**Comment by wabscale** [comment]
There isnt actually anything flask required here I dont think. We can jump on a call on discord and pull it over the finish line together if you want.

**Comment by wabscale** [comment]
rebased

**Pull request closed without merging**
