### PR TITLE
FIX do not remove the trailing line on termination

### PR DESCRIPTION
**Pull request by PIG208**
This occurs when the student output doesn't end with a newline and the qemu termination message happens to be at the same line.
The following demonstrates this error:
```
> from utils import trim
> stdout = """Booting from Hard Disk..xv6...
cpu0: starting
myprog test.txt
sb: size 1000 nblocks 941 ninodes 200 nlog 30 logstart 2 inodestart 32 bmap start 58
init: starting sh
$ Test1
Test2
Test3 
Test4$ qemu-system-i386: terminating on signal 15 from pid 1454 (timeout)"""
> trim(stdout)  # Test4 was removed
["Test1", "Test2", "Test3"]
```

Test cases were added to guarantee full test coverage for `trim`.

### CODE REVIEW

**Comment by wabscale** [comment]
Did you test these changes on the repo with the edge case that you find this issue with?

**Comment by PIG208** [comment]
Somehow the student output contains a null character, but I find that it's a problem with the student code.

**Comment by PIG208** [comment]
Just went through all the passing submissions we have (except the official solution), the autograde results are correct.

**Review by wabscale — APPROVED** [review]

**Comment by wabscale** [comment]
rebased

**Pull request closed without merging**
