### PR TITLE
ADD slack/discord daily report

### PR DESCRIPTION
**Pull request by AlpacaMax**
This PR is the result of discussions in #269 . All the SQL queries are implemented using `sqlalchemy` API so that it works for different databases. The code for querying number of students for each course and number of ides opened for each course is currently very inefficient and will be optimized in the future.

The scope of this PR is only limited to delivering daily report to the Anubis LMS Discord Server and possibly OS Slack Group. In future PRs Discord and Slack Bot commands will be introduced for some basic interactions with the backend of Anubis.

### CODE REVIEW

**Comment by wabscale** [comment]
Great stuff dude. You could have just used the raw SQL from the original issue. 

Also you should probably exclude the `TEST` and `DEMO` course from the cumulative results. For example, we should not count people that are signed up for the DEMO as students.

**Comment by AlpacaMax** [comment]
Just have a feeling that using `sqlalchemy` API function is more flexible. Though I don't really see any major difference.

**Comment by wabscale** [comment]
There will be a large difference in the amount of time it takes to execute. SQLAlchemy can have a whole lot of overhead. For this use case it does not matter though. For other places in Anubis where we have to query the database to get results back to a user quickly, it matters a lot.

**Comment by wabscale** [comment]
Done. Also yikes. Apt can be pretty annoying like that.

**Comment by AlpacaMax** [comment]
I think I finished everything I can do for this PR. We still need a yaml file for `bot.py`, which is the discord bot. @wabscale I guess I need your help writing that. I also wrote `report-cron.yml`(hope I wrote it correctly).

**Pull request merged**
