### PR TITLE
ADD privacy policy component 

### PR DESCRIPTION
**Pull request by dzhu7400**

### CODE REVIEW

**Comment by synoet** [comment]
Could you attach a screenshot?

**Review by synoet — CHANGES_REQUESTED** [review]
Please attach a screenshot and sign your commits.

**Comment by dzhu7400** [comment]
privacy_policy

**Comment by synoet** [comment]
> privacy_policy

We are gonna have to make the styles a bit nicer on the eyes. Maybe make it a paper and give it some padding and make the background the same background color we use everywhere else. Also add a small close button in the top right corner.

**Comment by dzhu7400** [comment]
privacy_policy_5
I've made some changes to make the style more appealing.

**Pull request closed without merging**
