### PR TITLE
CHG Implement a better clone command generator 

### PR DESCRIPTION
**Pull request by PIG208**
This adds support to the additional grouping feature for TAs to use the script to set up the repos on their local machines.
image

### CODE REVIEW

**Comment by AlpacaMax** [comment]
Idk if this happened to anyone else but when I try to clone assignments github will block me cuz my computer downloads them too fast. If this happens to a lot of people then I think it would be a good idea to just add sleeps in between clones.

**Comment by wabscale** [comment]
Quite excelent work, I'm going to check this out in detail later today.

@AlpacaMax do you clone over http? That may be your problem. I have never had that problem when clonging on ssh.

**Comment by AlpacaMax** [comment]
> Quite excelent work, I'm going to check this out in detail later today.
> 
> @AlpacaMax do you clone over http? That may be your problem. I have never had that problem when clonging on ssh.

Yeah I guess it's probably just me

**Comment by PIG208** [comment]
I'm not entirely sure if the CI failure is relevant to this PR. It seems to be a lock issue with Redis.

**Comment by wabscale** [comment]
I think we should probably consider giving TAs the ability to define their own groups. So like we store server side which groups are which, and maybe be able to name them too. Either way, this is an easy rebase for today.

**Comment by wabscale** [comment]
cloned.

**Comment by PIG208** [comment]
> I think we should probably consider giving TAs the ability to define their own groups. So like we store server side which groups are which, and maybe be able to name them too. Either way, this is an easy rebase for today.

Yeah, eventually. It is probably worth flatting out the design decision. This will do for now as we will get into the process of grading shortly.

**Pull request closed without merging**
