### PR TITLE
CHG Super Users Page to new components

### PR DESCRIPTION
**Pull request by ampahwa**
Edited format of Users page for superusers to match admin Students page while adding superuser functionality.
Modified ListHeader to align rows correctly.
Screenshot attached: 

S_users sc

### CODE REVIEW

**Comment by synoet** [comment]
Please attach a screenshot.

And rebase to remove unnecessary commits.

**Comment by synoet** [comment]
Also please sign your commits.

**Review by synoet — CHANGES_REQUESTED** [review]
This looks good, but I think that the "Log in As" should be a button with some icon.

Maybe this icon `import ExitToAppIcon from '@material-ui/icons/ExitToApp';` from mui.

**Comment by ampahwa** [comment]
Changed icon, sc attached: 


sc login

**Review by synoet — APPROVED** [review]
We also probably want to add the search and pagination functionality to this page. But lets leave that for another issue.

Good Job.

**Pull request closed without merging**
